/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const StudioTest = (props) => {
    const { nodes, materials } = useGLTF("/studioTest.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Carpet.geometry}
                material={materials.Carpet}
                position={[2.44, 0.23, 1.79]}
                scale={[1, 0.52, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Shelf.geometry}
                material={materials["Dark Wood"]}
                position={[0.43, 1.86, 1.06]}
                rotation={[0, 0, -Math.PI / 2]}
            />
            <group position={[1.57, 0.11, 1.53]} scale={[1.01, 1, 1]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003.geometry}
                    material={materials.Floor}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003_1.geometry}
                    material={materials["Wall Outer"]}
                />
            </group>
            <group position={[1.45, 1.54, 0.12]} rotation={[1.57, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004.geometry}
                    material={materials["Wall Material"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004_1.geometry}
                    material={materials["Wall Outer"]}
                />
            </group>
            <group position={[0.12, 1.54, 1.63]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005_1.geometry}
                    material={materials["Wall Material"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005_2.geometry}
                    material={materials["Wall Outer"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Frame.geometry}
                material={materials["Dark Wood"]}
                position={[1.25, 1.79, 0.05]}
                rotation={[3.14, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Window_Glass.geometry}
                material={materials.Metallic}
                position={[1, 1.8, 0.05]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[1, 1.61, 0.91]}
            />
            <group position={[0.56, 0.57, 1.7]} rotation={[0, Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010.geometry}
                    material={materials["Dark Wood"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010_1.geometry}
                    material={materials.Handle}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Table_Leg.geometry}
                material={materials["Dark Wood"]}
                position={[0.58, 0.57, 0.26]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <group position={[0.61, 0.8, 1.7]} rotation={[0, Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube026.geometry}
                    material={materials["Dark Wood"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube026_1.geometry}
                    material={materials.Handle}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bin.geometry}
                material={materials["Bin Metallic"]}
                position={[0.48, 0.39, 0.54]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Desk.geometry}
                material={materials["Dark Wood"]}
                position={[0.58, 0.94, 1.07]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chair_Top.geometry}
                material={materials["Chair Legs"]}
                position={[1.49, 0.65, 1]}
                rotation={[0, -0.51, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chair_Bar.geometry}
                material={materials["Bin Metallic"]}
                position={[1.5, 0.32, 0.99]}
                rotation={[0, -0.51, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Chair_Legs.geometry}
                material={materials["Chair Legs"]}
                position={[1.48, 0.29, 1.24]}
                rotation={[Math.PI, -1.33, Math.PI]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bed_Frame.geometry}
                material={materials["Dark Wood"]}
                position={[2.56, 0.51, 2.96]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bed_Mattress.geometry}
                material={materials.Mattress}
                position={[1.45, 0.66, 2.46]}
            />
            <group position={[0.37, 1.13, 2.86]} rotation={[Math.PI / 2, 0, -1.57]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube031.geometry}
                    material={materials.Metallic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube031_1.geometry}
                    material={materials["Bin Metallic"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bed_Sheet.geometry}
                material={materials["Bed Sheet"]}
                position={[1.5, 1.24, 2.47]}
                scale={[1.41, 1, 0.9]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Pillow.geometry}
                material={materials.Pillow}
                position={[0.52, 0.87, 2.47]}
                rotation={[0, 0, -0.68]}
                scale={[0.22, 0.28, 0.42]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Laptop_Bottom.geometry}
                material={materials.Laptop}
                position={[0.64, 0.96, 1.01]}
                rotation={[0, 1.05, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Laptop_Keyboard.geometry}
                material={materials.Material}
                position={[0.47, 0.96, 1.12]}
                rotation={[0.04, 1.05, -0.04]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Laptop_Top.geometry}
                material={materials.Laptop}
                position={[0.47, 1.09, 0.92]}
                rotation={[-1.82, -0.41, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Laptop_Screen.geometry}
                material={materials.Screen}
                position={[0.47, 1.09, 0.92]}
                rotation={[-1.82, -0.41, -2.14]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Desk_Lamp_Stand.geometry}
                material={materials["Bin Metallic"]}
                position={[0.48, 0.97, 0.41]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Desk_Lamp.geometry}
                material={materials["Bin Metallic"]}
                position={[0.41, 1.19, 0.41]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Desk_Lamp_Light.geometry}
                material={materials["Bin Metallic"]}
                position={[0.41, 1.19, 0.41]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube005.geometry}
                material={nodes.Cube005.material}
                position={[1.71, 1.14, 0.43]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[1.33, 1, 1.33]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube007.geometry}
                material={nodes.Cube007.material}
                position={[0.91, 1.02, 0.43]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube008.geometry}
                material={nodes.Cube008.material}
                position={[0.46, 1.03, 1.71]}
                rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube011.geometry}
                material={nodes.Cube011.material}
                position={[2.58, 1.93, 0.45]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube012.geometry}
                material={nodes.Cube012.material}
                position={[2.9, 1.93, 0.46]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube013.geometry}
                material={nodes.Cube013.material}
                position={[2.78, 0.23, 1.26]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube018.geometry}
                material={nodes.Cube018.material}
                position={[0.41, 2.07, 0.62]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube020.geometry}
                material={nodes.Cube020.material}
                position={[0.41, 1.98, 1.74]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009.geometry}
                material={nodes.Cube009.material}
                position={[2.19, 2.01, 0.43]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Globe_Stand.geometry}
                material={materials["Globe Holder"]}
                position={[0.42, 1.9, 0.41]}
                rotation={[0, -0.53, 0]}
                scale={[0.1, 0.01, 0.1]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Globe_Holder.geometry}
                    material={materials["Globe Holder"]}
                    position={[-0.01, 24.45, 0.19]}
                    rotation={[0, 0, -Math.PI / 2]}
                    scale={[17.39, 3.05, 2.23]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Globe_Sphere.geometry}
                    material={materials.Globe}
                    position={[-0.01, 24.4, 0.18]}
                    scale={[1.34, 10.47, 1.34]}
                />
            </mesh>
            <group position={[0.79, 1, 0.62]} rotation={[0, 0.69, 0]} scale={0.04}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004.geometry}
                    material={materials.Mug}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004_1.geometry}
                    material={materials.Coffee}
                />
            </group>
            <group
                position={[1.05, 1, 0.34]}
                rotation={[0, 1.16, 0]}
                scale={[-0.04, -0.07, -0.04]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder005.geometry}
                    material={materials["Bin Metallic"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder005_1.geometry}
                    material={materials["Can Label"]}
                />
            </group>
            <group position={[0.76, 1.02, 1.8]} rotation={[0, 1.04, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube042.geometry}
                    material={materials["Alarm Clock Box"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube042_1.geometry}
                    material={materials["Alarm Clock Face"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube042_2.geometry}
                    material={materials["Alarm Clock Button"]}
                />
            </group>
            <group position={[0.71, 1.01, 0.32]} scale={0.05}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder006.geometry}
                    material={materials["Candle Container"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder006_1.geometry}
                    material={materials["Bin Metallic"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder006_2.geometry}
                    material={materials["Candle Wax"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder006_3.geometry}
                    material={materials["Candle Wick"]}
                />
            </group>
            <group
                position={[0.39, 0.96, 1.44]}
                rotation={[-Math.PI, 1.15, -Math.PI]}
                scale={1.17}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube044.geometry}
                    material={materials["Make Up Container"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube044_1.geometry}
                    material={materials["Make Up Powder 1"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube044_2.geometry}
                    material={materials["Make Up Powder 2"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube044_3.geometry}
                    material={materials["Make Up Powder 3"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube044_4.geometry}
                    material={materials["Make Up Powder 4"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube044_5.geometry}
                    material={materials.Metallic}
                />
            </group>
            <group
                position={[0.5, 0.96, 1.47]}
                rotation={[0, 0.42, 0]}
                scale={[0.03, 0, 0.03]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder007.geometry}
                    material={materials["Make Up Container"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder007_1.geometry}
                    material={materials["Make Up Powder 3"]}
                />
            </group>
            <group
                position={[0.47, 0.97, 1.4]}
                rotation={[-Math.PI, 1.15, -Math.PI]}
                scale={1.17}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube045.geometry}
                    material={materials["Bin Metallic"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube045_1.geometry}
                    material={materials["Make Up Bottle"]}
                />
            </group>
            <group position={[0.49, 0.96, 0.59]} rotation={[0, Math.PI / 2, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube046.geometry}
                    material={materials["Pencil Container"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube046_1.geometry}
                    material={materials["Pencil 1"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube046_2.geometry}
                    material={materials["Pencil 2"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube046_3.geometry}
                    material={materials["Pencil 3"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube046_4.geometry}
                    material={materials["Pencil Container Inside"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bookshelf.geometry}
                material={materials["Dark Wood"]}
                position={[2.51, 1.3, 0.42]}
                rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bookshelf_Door.geometry}
                material={materials["Dark Wood"]}
                position={[2.51, 0.93, 0.63]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.38, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Bookshelf_Door_Handles.geometry}
                material={materials.Handle}
                position={[2.56, 0.95, 0.78]}
                rotation={[-0.03, 0, -Math.PI / 2]}
                scale={[0.06, 0.04, 0.04]}
            />
            <group
                position={[3.01, 1.25, 0.44]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={0.86}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube049.geometry}
                    material={materials["Book Cover 3"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube049_1.geometry}
                    material={materials["Book Cover 1"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube049_2.geometry}
                    material={materials["Book Cover 2"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube049_3.geometry}
                    material={materials["Book Cover 4"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube049_4.geometry}
                    material={materials["Book Cover 5"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube049_5.geometry}
                    material={materials["Book Paper"]}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Board.geometry}
                material={materials["Material.001"]}
                position={[0.26, 1.35, 1.24]}
                rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Whiteboard.geometry}
                material={materials.Whiteboard}
                position={[0.26, 1.35, 1.23]}
                rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curtains.geometry}
                material={materials.Curtains}
                position={[0.88, 1.89, 0.27]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.75, 0.75, 0.63]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Curtain_Holder.geometry}
                material={materials["Dark Wood"]}
                position={[1.27, 2.51, 0.26]}
                rotation={[1.57, 0, 0]}
                scale={[1, 0.58, 1.41]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Poster.geometry}
                material={materials.Poster}
                position={[0.23, 1.86, 2.46]}
                rotation={[0, 0, -Math.PI / 2]}
            />
        </group>
    );
}

useGLTF.preload("/studioTest.glb");